# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  config.vm.synced_folder "../", "/data/web/", type: "rsync",
    rsync__exclude: [ '.git', 'logs' , 'web/js', 'web/bundles' , 'app/logs' , '/vendor/' , 'composer.phar' , 'app/cache'],
    rsync__args: ["--verbose", "--archive", "--delete", "-z", "--copy-links"],
    rsync__chown: false

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "hashicorp/precise32"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network "forwarded_port", guest: 80, host: 9000


if Vagrant.has_plugin?("vagrant-gatling-rsync")
    config.gatling.rsync_on_startup = false
  end
end

# vagrant gatling-rsync-auto
